version: "3"
services:
  psqldb:
    container_name: psqldb
    image: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mydatabase:
  