"""fix userid column name

Revision ID: c5693f3759fa
Revises: c83467287379
Create Date: 2024-10-31 16:03:55.289886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5693f3759fa'
down_revision: Union[str, None] = 'c83467287379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_token', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('verification_token', 'identifier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_token', 'identifier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('verification_token', 'id')
    # ### end Alembic commands ###
