"""fix userid column name

Revision ID: c83467287379
Revises: 4de72c85ef49
Create Date: 2024-10-31 16:03:03.578159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83467287379'
down_revision: Union[str, None] = '4de72c85ef49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_token', 'identifier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_token', 'identifier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
